# Generated by Django 5.1 on 2024-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='bookedDate',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='token',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
