# Generated by Django 5.1 on 2024-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookingmodel_bookeddate_bookingmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='count',
            field=models.IntegerField(default=None),
        ),
    ]
